Added workflow to publish to npm
lidofinance/evm-script-decoder pull request #3
Opened 2022-10-17 12:27 UTC by kozlovzxc-at-lido

# Description

- removed lib folder, since we shouldn't make commits to the repo itself from the workflow.
- using environment, so NPM_TOKEN is only accessible from master branch.
- publishing only package.json & lib folders, just not to bloat node_modules with original code for applications, which are using this package.
- Changed name from `evm-script-decoder` to `@lidofinance/evm-script-decoder`, so we are using our protected namespace.

Further steps to take:
- Pick next version automatically via https://github.com/semantic-release/semantic-release.
- Run tests/linters/formatters as a part of CI.

2022-10-17 14:11 UTC, skhomuti requested changes

2022-10-17 14:11 UTC, skhomuti commented on .github/workflows/release.yml
> +        uses: actions/checkout@v3
add `persist-credentials: false` to all checkout steps

2022-10-17 15:03 UTC, skhomuti approved these changes

2022-10-17 20:40 UTC, Psirex approved these changes

2022-10-18 11:31 UTC, manneredboor approved these changes

2022-10-18 12:02 UTC, merged